### ISSUE TITLE
Use NODEJS_20_X

### ISSUE THREAD

**Issue by trivikr** [aws-samples/mlops-e2e#70] opened 2024-06-13 20:33 UTC
**Is your feature request related to a problem? Please describe.**

Lambda NODEJS_14_X runtime is used at multiple places https://github.com/search?q=repo%3Aaws-samples%2Fmlops-e2e%20NODEJS_14_X&type=code

It's function create is blocked as of `Jan 9, 2024`.
Lambda Supported Runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Describe the solution you'd like**

Use NODEJS_20_X, which [was made available on Nov 15, 2023](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

**Comment by imsalmanmalik** [comment] 2024-08-05 07:19
despite making changes the deploy stage of the Code pipeline keeps failing as CFT still detects NodeJS_14_X runtime although all references have been changed to older node js version. Tried to build the lock files and node_modules from scratch yet the issue persists and made relevant changes within the model_deploy/lib/modelDeploymentStack.ts lambda runtime as well.

**Comment by MABatin** [comment] 2024-09-13 15:18
> despite making the changes, deploy stage of the Code pipeline keeps failing as CFT still detects NodeJS_14_X runtime although all references have been changed to older node js version. Tried to build the lock files and node_modules from scratch yet the issue persists and made relevant changes within the model_deploy/lib/modelDeploymentStack.ts lambda runtime as well.

Hi could you solve your issue or is it still persistant? Also did you try NodeJS_18_X runtime?

**Comment by imsalmanmalik** [comment] 2024-09-13 20:12
The issue is still persistent. Stopped trying after a while though.

**Comment by jessieweiyi** [comment] 2024-09-19 06:35
PR #79 upgrades the lambda runtime to 18.X. Close this issue.

**Closed by jessieweiyi** 2024-09-19 06:35 UTC
Labels: enhancement
